nodeLinker: node-modules

npmScopes:
  voltz-protocol:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.5.0.cjs
