[profile.default]
    src = 'contracts/vamm'
    out = 'out'
    libs = ['node_modules', 'lib']
    test = 'test'
    cache_path  = 'cache_forge'
    via_ir = true
    fuzz = { runs = 256 }
    optimizer = true
    optimizer_runs = 10_000