# owner is required and must be overridden
[setting.owner]
description = "Admin user for the protocol"

# Deploys an initial VAMM Proxy so that a new VAMM Proxy is not 
# re-deployed every time we deploy a new router. Implementation is
# then upgraded to the correct Router implementation in the
# invoke.upgrade_vamm_proxy command below.
[contract.InitialVammProxy]
artifact = "VammProxy"
args = ["<%= contracts.OwnerUpgradeModule.address %>", "<%= settings.owner %>"]
abiOf = ["OwnerUpgradeModule"]
salt = "<%= settings.salt %>"
create2 = true
depends = ["contract.OwnerUpgradeModule"]

# Upgrades implementation of VAMM Proxy to point to the new 
# router implementation.
[invoke.upgrade_vamm_proxy]
target = ["InitialVammProxy"]
abi = "UpgradeModule"
from = "<%= settings.owner %>"
func = "upgradeTo"
args = ["<%= contracts.VammRouter.address %>"]
factory.VammProxy.abiOf = ["VammRouter"]
factory.VammProxy.event = "Upgraded"
factory.VammProxy.arg = 0
depends = [
  "contract.InitialVammProxy",
  "router.VammRouter"
]