name: "Release"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: "ubuntu-latest"
    permissions:
      packages: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "lts/*"

      - name: "Install the Node.js dependencies"
        run: "yarn install --immutable"
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Bump versions"
        run: "yarn bump"

      - run: "yarn publish"
        env:
            NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}