name: "Release"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: "ubuntu-latest"
    permissions:
      packages: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Setup GitHub package registry"
        run: yarn config set npmRegistries --json '{"https://npm.pkg.github.com/":{"npmAuthToken":"${{secrets.NPM_AUTH_TOKEN}}"}}'

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: 18
          always-auth: true

      - name: "Install the Node.js dependencies"
        run: "yarn install --immutable"

      - name: "Release"
        run: "yarn release"
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

      - name: "Change npm registry server"
        run: "yarn config set npmRegistryServer https://npm.pkg.github.com"

      - run: "yarn publish"
